# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tlN1ew6oW7yeqkjmbmC0KxaqygMKP0R
"""

import streamlit as st
import pickle
import numpy as np

# ========== LOAD MODEL & PREPROCESSOR ==========
@st.cache_resource
def load_artifacts():
    with open('svm_model.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('tfidf_vectorizer.pkl', 'rb') as f:
        vectorizer = pickle.load(f)
    with open('label_encoder.pkl', 'rb') as f:
        le = pickle.load(f)
    return model, vectorizer, le

model, vectorizer, le = load_artifacts()

# ========== CONFIG PAGE ==========
st.set_page_config(
    page_title="SVM Sentiment Analysis",
    layout="wide"
)

st.title("💬 Sentiment Analysis dengan SVM (TF‑IDF)")
st.write("Masukkan teks bahasa Indonesia untuk diklasifikasikan menjadi **Positif** atau **Negatif**.")

# ========== INPUT USER ==========
col1, col2 = st.columns([2,1])

with col1:
    text = st.text_area(
        "Teks ulasan / komentar:",
        height=150,
        placeholder="Contoh: Pelayanannya cepat dan sangat memuaskan..."
    )

    threshold = st.slider("Threshold confidence positif", 0.1, 0.9, 0.5, 0.05)

    if st.button("Prediksi Sentimen"):
        if text.strip() == "":
            st.warning("Masukkan teks terlebih dahulu.")
        else:
            # Transform & predict
            X_vec = vectorizer.transform([text])
            proba = model.predict_proba(X_vec)[0]
            pred  = model.predict(X_vec)[0]

            # Label & confidence
            label = le.inverse_transform([pred])[0]
            conf  = float(np.max(proba))

            st.subheader("Hasil Prediksi")
            st.write(f"**Sentimen:** {label}")
            st.write(f"**Confidence:** {conf:.2%}")

            st.progress(conf)

            st.write("Probabilitas:")
            st.write(f"- Positif: {proba[1]:.2%}")
            st.write(f"- Negatif: {proba[0]:.2%}")

with col2:
    st.subheader("Contoh Cepat")
    examples = [
        "sangat bagus pelayanannya",
        "parah sekali, tidak akan beli lagi",
        "biasa saja, tidak terlalu istimewa"
    ]

    for ex in examples:
        X_ex = vectorizer.transform([ex])
        proba_ex = model.predict_proba(X_ex)[0]
        pred_ex  = le.inverse_transform(model.predict(X_ex))[0]
        conf_ex  = float(np.max(proba_ex))

        st.write(f"**Teks:** {ex}")
        st.write(f"Prediksi: `{pred_ex}` (conf: {conf_ex:.2%})")
        st.markdown("---")

st.caption("App ini menggunakan SVM + TF‑IDF dan dapat dengan mudah di-deploy ke cloud.")